apiVersion: v1
kind: Service
metadata:
  name: {{ include "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
  selector:
    {{- include "php.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "php.fullname" . }}ssh
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  ports:
    - port: 22
      nodePort: 31628
  selector:
    {{- include "php.selectorLabels" . | nindent 4 }}
  type: NodePort