apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-php-secret"
type: Opaque
data:
  magento-user: {{ .Values.magento.user | b64enc | quote }}
  magento-password: {{ .Values.magento.password | b64enc | quote }}
  magento-adminuri: {{ .Values.magento.admin_uri | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{ if .Values.rabbitmq.enabled }}
  rabbitmq-password: {{ .Values.rabbitmq.pass | b64enc | quote }}
  {{ end }}
  {{ if .Values.elasticsearch.auth.enabled }}
  elasticsearch-password: {{ .Values.elasticsearch.auth.password | b64enc | quote }}
  {{ end }}