apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-php-shared-code-pvc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persisted.storage.code }}

{{ if .Values.persisted.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-php-media-pvc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persisted.storage.media }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-php-generated-pvc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persisted.storage.generated }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-php-config-pvc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persisted.storage.config }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-php-var-pvc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persisted.storage.var }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-php-static-pvc"
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persisted.storage.static_content }}
{{ end }}