apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "varnish.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}