apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}redis"
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  ports:
  - port: 6379
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  clusterIP: None