apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        args:
          - "--appendonly yes"
        ports:
        - containerPort: 6379
          name: redis
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.persisted.enabled -}}
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
        {{- end }}
      {{- if .Values.persisted.enabled -}}
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-redis-pvc"
      {{- end }}